# -*- coding: utf-8 -*-
"""outs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TsqADxKWB0nrKy6oSMbbn0mK4zYEJzRL
"""

#import cv2
#import numpy as np

#img = cv2.imread('/root/Desktop/leaf.jpg',0)
#ret,thr = cv2.threshold(img, 0, 255, cv2.THRESH_OTSU)
#cv2.imshow('win1', thr)
#cv2.waitKey(0)  
#cv2.destroyAllWindows()
import cv2

import os,glob

from os import listdir,makedirs

from os.path import isfile,join
path = 'bi Leafsmut' # Source Folder
dstpath = 'outs Leafsmut' # Destination Folder
try:
    makedirs(dstpath)
except:
    print ("Directory already exist, images will be written in same folder")
# Folder won't used
files = [f for f in listdir(path) if isfile(join(path,f))] 
for image in files:
    try:
        img = cv2.imread(os.path.join(path,image))
        gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        ret,thr = cv2.threshold(gray, 0, 255, cv2.THRESH_OTSU)
        dstPath = join(dstpath,image)
        cv2.imwrite(dstPath,thr)
    except:
        print ("{} is not converted".format(image))
for fil in glob.glob("*.jpg"):
    try:
        image = cv2.imread(fil) 
        gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
        ret,thrr = cv2.threshold(gray_image, 0, 255, cv2.THRESH_OTSU)# convert to greyscale
        cv2.imwrite(os.path.join(dstpath,fil),thrr)
    except:
        print('{} is not converted')